# Generated by Django 3.1.2 on 2020-10-10 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gategory_name', models.CharField(blank=True, max_length=222, null=True, unique=True)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='FoodItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(blank=True, max_length=222, null=True, unique=True)),
                ('discription', models.CharField(blank=True, max_length=222, null=True, unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('is_veg', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('delivery_partener', models.CharField(max_length=22, null=True)),
                ('item_rating', models.CharField(max_length=22, null=True)),
                ('gategory_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='urban_backend.category')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
