# Generated by Django 3.1.2 on 2020-10-10 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urban_backend', '0003_auto_20201010_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='gategory_name',
            new_name='category_name',
        ),
    ]
