# Generated by Django 3.1.2 on 2020-10-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urban_backend', '0004_auto_20201010_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_veg',
        ),
        migrations.AddField(
            model_name='fooditems',
            name='is_veg',
            field=models.BooleanField(default=False),
        ),
    ]
