# Generated by Django 3.1.2 on 2020-10-11 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urban_backend', '0005_auto_20201010_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditems',
            old_name='gategory_name',
            new_name='category_name',
        ),
    ]
